# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle 	  		T_(n)=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
# Pentagonal 	  	P_(n)=n(3n-1)/2 	1, 5, 12, 22, 35, ...
# Hexagonal 	  	H_(n)=n(2n-1) 	  	1, 6, 15, 28, 45, ...

# It can be verified that T_(285) = P_(165) = H_(143) = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.

#triangle
def T(n):
    return n*(n+1)/2
	
#pentagonal	
def P(n):
    return n*(3*n-1)/2

#hexagonal
def H(n):
    return n*(2*n-1)

for i in range(2500000):
    a = H(i)
    ii = 1
    b = P(ii)
    while b <= a:	    
	    if b == a:
		    iii = 1
		    c = T(iii)
		    while c <= b:
			    if c == b:
				    print i, ii, iii, a
			    c = T(iii)
			    iii += 1
	    ii += 1
	    b = P(ii)

print T(285)
print P(165)
print H(143)