#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#Find the sum of all the even-valued terms in the sequence which do not exceed four million.
sum = 2
ant = 1
num = 2
while True:
    t = num
    num = num + ant	
    ant = t    
    if num > 4000000:
	    break
    if num % 2 == 0:
	    print num
	    sum = sum + num

print sum